elasticsearch:
  esJavaOpts: "-Xms512m -Xmx512m"

  minimumMasterNodes: 1

  protocol: https

  replicas: 1

  security:
    enabled: true
    tls:
      enabled: true

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
