apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-gitops
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Preetix28/gitops-demo.git
    targetRevision: master
    path: environments/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
