airflow:
  executor: CeleryExecutor

  apiServer:
    service:
      type: NodePort

  dags:
    persistence:
      enabled: false

  logs:
    persistence:
      enabled: false

  postgresql:
    enabled: true

  redis:
    enabled: true

  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false

  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false

