apiVersion: v2
name: dev
description: Development environment
type: application
version: 0.1.0

dependencies:
  - name: nginx
    version: 0.1.0
    repository: "file://../../apps/nginx"

  - name: grafana
    version: 0.1.0
    repository: "file://../../apps/grafana"

  - name: elasticsearch
    version: 0.1.0
    repository: "file://../../apps/elasticsearch"
