nginx:
  replicaCount: 1

grafana:
  grafana:
    replicas: 1

elasticsearch:
  elasticsearch:
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: microk8s-hostpath
